name: "setup-pesde"
description: "Installs pesde (and optionally Lune) in GitHub actions"
branding:
  icon: "download"
  color: "orange"

inputs:
  version:
    description: "Version of pesde to install"
  lune-version:
    description: "Version of lune to install"
  token:
    description: "A GitHub token, used to access the API and avoid ratelimits (defaults to `github.token`)"
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  cache:
    description: "Whether to cache package directories and the pesde index (defaults to false)"
    default: false
  home:
    description: "Directory where pesde should store its CAS, binaries, and other data (defaults to $PESDE_HOME)"
  cwd:
    description: "Base directory where the pesde project is located (defaults to $GITHUB_WORKSPACE)"
    default: ${{ github.workspace }}
runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/index.js"
